ALTER TRIGGER changewatcher disable;
ALTER TRIGGER dealschanged disable;
ALTER TRIGGER systemtrigger disable;

drop table "SYSTEM"."COMISSIONCHANGED";
drop table "SYSTEM"."DEALSCHANGED";
drop table "SYSTEM"."DATABASECHANGED";

--------------------------------------------------------
--  DDL for Table COMISSIONCHANGED
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COMISSIONCHANGED" 
   (	"OLD_VALUE" NUMBER, 
	"NEW_VALUE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  --------------------------------------------------------
--  DDL for Table DEALSCHANGED
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DEALSCHANGED" 
   (	"OPERATION_DATE" DATE, 
	"OPERATION_KIND" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
--------------------------------------------------------
--  DDL for Table DATABASECHANGED
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DATABASECHANGED" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"OBJECT_TYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
ALTER TRIGGER changewatcher enable;
ALTER TRIGGER dealschanged enable;
ALTER TRIGGER systemtrigger enable; 
  

