-- MySQL Script generated by MySQL Workbench
-- 10/13/15 13:15:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `idCountry` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idCountry`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`City` ;

CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Country_idCountry` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCity`, `Country_idCountry`)  COMMENT '',
  INDEX `fk_City_Country_idx` (`Country_idCountry` ASC)  COMMENT '',
  CONSTRAINT `fk_City_Country`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `mydb`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Adress` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Adress` (
  `idAdress` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Street` VARCHAR(45) NULL COMMENT '',
  `House` VARCHAR(10) NULL COMMENT '',
  `City_idCity` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idAdress`, `City_idCity`)  COMMENT '',
  INDEX `fk_Adress_City1_idx` (`City_idCity` ASC)  COMMENT '',
  CONSTRAINT `fk_Adress_City1`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `mydb`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Adress_idAdress` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCompany`, `Adress_idAdress`)  COMMENT '',
  INDEX `fk_Company_Adress1_idx` (`Adress_idAdress` ASC)  COMMENT '',
  CONSTRAINT `fk_Company_Adress1`
    FOREIGN KEY (`Adress_idAdress`)
    REFERENCES `mydb`.`Adress` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Firstname` VARCHAR(45) NULL COMMENT '',
  `Surname` VARCHAR(45) NULL COMMENT '',
  `BirthDate` DATE NULL COMMENT '',
  PRIMARY KEY (`idClient`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeOfTour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TypeOfTour` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TypeOfTour` (
  `idTypeOfTour` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTypeOfTour`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Insurance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Insurance` (
  `idInsurance` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Cost` DOUBLE NULL COMMENT '',
  `Insurancecol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idInsurance`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tour` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tour` (
  `idTour` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Cost` DOUBLE NULL COMMENT '',
  `TypeOfTour_idTypeOfTour` INT NOT NULL COMMENT '',
  `Company_idCompany` INT NOT NULL COMMENT '',
  `Insurance_idInsurance` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTour`, `TypeOfTour_idTypeOfTour`, `Company_idCompany`, `Insurance_idInsurance`)  COMMENT '',
  INDEX `fk_Tour_TypeOfTour1_idx` (`TypeOfTour_idTypeOfTour` ASC)  COMMENT '',
  INDEX `fk_Tour_Company1_idx` (`Company_idCompany` ASC)  COMMENT '',
  INDEX `fk_Tour_Insurance1_idx` (`Insurance_idInsurance` ASC)  COMMENT '',
  CONSTRAINT `fk_Tour_TypeOfTour1`
    FOREIGN KEY (`TypeOfTour_idTypeOfTour`)
    REFERENCES `mydb`.`TypeOfTour` (`idTypeOfTour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tour_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tour_Insurance1`
    FOREIGN KEY (`Insurance_idInsurance`)
    REFERENCES `mydb`.`Insurance` (`idInsurance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company_has_Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company_has_Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company_has_Client` (
  `Company_idCompany` INT NOT NULL COMMENT '',
  `Client_idClient` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Company_idCompany`, `Client_idClient`)  COMMENT '',
  INDEX `fk_Company_has_Client_Client1_idx` (`Client_idClient` ASC)  COMMENT '',
  INDEX `fk_Company_has_Client_Company1_idx` (`Company_idCompany` ASC)  COMMENT '',
  CONSTRAINT `fk_Company_has_Client_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Company_has_Client_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `idHotel` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `StarsCount` INT NULL COMMENT '',
  `Adress_idAdress` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idHotel`, `Adress_idAdress`)  COMMENT '',
  INDEX `fk_Hotel_Adress1_idx` (`Adress_idAdress` ASC)  COMMENT '',
  CONSTRAINT `fk_Hotel_Adress1`
    FOREIGN KEY (`Adress_idAdress`)
    REFERENCES `mydb`.`Adress` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Room` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `idRoom` VARCHAR(20) NOT NULL COMMENT '',
  `CostPerDay` DOUBLE NULL COMMENT '',
  `Hotel_idHotel` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idRoom`, `Hotel_idHotel`)  COMMENT '',
  INDEX `fk_Room_Hotel1_idx` (`Hotel_idHotel` ASC)  COMMENT '',
  CONSTRAINT `fk_Room_Hotel1`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RoomReservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RoomReservation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RoomReservation` (
  `idRoomReservation` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `From` DATE NULL COMMENT '',
  `To` DATE NULL COMMENT '',
  `CurrentCostPerDay` DOUBLE NULL COMMENT '',
  `Room_idRoom` VARCHAR(20) NOT NULL COMMENT '',
  `Client_idClient` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idRoomReservation`, `Room_idRoom`, `Client_idClient`)  COMMENT '',
  INDEX `fk_RoomReservation_Room1_idx` (`Room_idRoom` ASC)  COMMENT '',
  INDEX `fk_RoomReservation_Client1_idx` (`Client_idClient` ASC)  COMMENT '',
  CONSTRAINT `fk_RoomReservation_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `mydb`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoomReservation_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TourReservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TourReservation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TourReservation` (
  `idTourReservation` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `From` DATE NULL COMMENT '',
  `To` DATE NULL COMMENT '',
  `CurrentCost` DOUBLE NULL COMMENT '',
  `Tour_idTour` INT NOT NULL COMMENT '',
  `Client_idClient` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTourReservation`, `Tour_idTour`, `Client_idClient`)  COMMENT '',
  INDEX `fk_TourReservation_Tour1_idx` (`Tour_idTour` ASC)  COMMENT '',
  INDEX `fk_TourReservation_Client1_idx` (`Client_idClient` ASC)  COMMENT '',
  CONSTRAINT `fk_TourReservation_Tour1`
    FOREIGN KEY (`Tour_idTour`)
    REFERENCES `mydb`.`Tour` (`idTour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TourReservation_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tour_has_City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tour_has_City` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tour_has_City` (
  `Tour_idTour` INT NOT NULL COMMENT '',
  `City_idCity` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Tour_idTour`, `City_idCity`)  COMMENT '',
  INDEX `fk_Tour_has_City_City1_idx` (`City_idCity` ASC)  COMMENT '',
  INDEX `fk_Tour_has_City_Tour1_idx` (`Tour_idTour` ASC)  COMMENT '',
  CONSTRAINT `fk_Tour_has_City_Tour1`
    FOREIGN KEY (`Tour_idTour`)
    REFERENCES `mydb`.`Tour` (`idTour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tour_has_City_City1`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `mydb`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
